version: '3'
services:
  streamlit_app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
      - $HOME/.aws:/root/.aws:ro
    environment:
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    command: streamlit run /app/main.py